[theme]
# primary accent color for interective elements.
primaryColor = "#ff5d56"

# background color for the main content area.
backgroundColor = "#111"

# background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#fff"